In [94]:
import torch

torch.cuda.is_available()

False

In [5]:
a = [1.0,2.0,1.0]
a[0]

1.0

In [6]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [7]:
import torch
a = torch.ones(3)
a


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "d:\pytorch\.venv\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "d:\pytorch\.venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "d:\pytorch\.venv\Lib\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "d:\pytorch\.venv\Lib\site-packages\tornado\platform\asyncio.py

tensor([1., 1., 1.])

In [8]:
#예시
import torch

b = torch.ones(4)
b

tensor([1., 1., 1., 1.])

In [9]:
print(b[1],float(b[1]))
print(int(b[1]))

tensor(1.) 1.0
1


In [10]:
b[2]=2
b[3]=3.0
b

tensor([1., 1., 2., 3.])

In [11]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points


tensor([4., 1., 5., 3., 2., 1.])

In [12]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [13]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
points.shape

torch.Size([3, 2])

In [15]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [16]:
points[1:,0:1]

tensor([[5.],
        [2.]])

In [17]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [18]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126,0.7152,0.0722])

In [19]:
batch_t = torch.randn(2,3,5,5)

In [20]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [21]:
unsqeezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqeezed_weights)
batch_weights = (batch_t * unsqeezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqeezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [22]:
import torch
tensor = torch.tensor([[1, 2], [3, 4]])
summed_tensor0 = tensor.sum(0)
summed_tensor1 = tensor.sum(1)
print(summed_tensor0, summed_tensor1)  # 출력: tensor([4, 6])


tensor([4, 6]) tensor([3, 7])


In [23]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw',img_t,weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw',batch_t,weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [24]:
weights_named = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

C:\Users\user\AppData\Local\Temp\ipykernel_16068\1804826620.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1924.)
  weights_named = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [25]:
#예시
ex_tensor = torch.tensor([[1.0, 1.1], [1.2, 1.3]], names = ['dim0','dim1'])
ex_tensor

tensor([[1.0000, 1.1000],
        [1.2000, 1.3000]], names=('dim0', 'dim1'))

In [26]:
#예시
ex1_tensor = torch.zeros(2,3,4,4)
ex1_tensor_names = ex1_tensor.refine_names(...,'rows','colimns')
ex1_tensor_None = ex1_tensor_names.rename(...,None)
ex1_tensor.shape, ex1_tensor.names, ex1_tensor_names.names, ex1_tensor_None.names

(torch.Size([2, 3, 4, 4]),
 (None, None, None, None),
 (None, None, 'rows', 'colimns'),
 (None, None, 'rows', None))

In [27]:
img_named = img_t.refine_names(...,'channels','rows','columns')
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print('img name:',img_named.shape,img_named.names)
print('batch name:',batch_named.shape,batch_named.names)

img name: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch name: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [28]:
weights_aligned = weights_named.align_as(img_named)
weights_named.shape,weights_aligned.shape,weights_aligned.names

(torch.Size([3]), torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [29]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [30]:
ex2_tensor = torch.zeros
ex2_tensor

<function torch._VariableFunctionsClass.zeros>

In [31]:
# 기본 데이터 타입인 float32로 2x3 텐서 생성
tensor_default = torch.zeros(2, 3)
print(tensor_default)
print(tensor_default.dtype)

# int32 데이터 타입으로 2x3 텐서 생성
tensor_int32 = torch.zeros(2, 3, dtype=torch.int32)
print(tensor_int32)
print(tensor_int32.dtype)

# float64 데이터 타입으로 2x3 텐서 생성
tensor_float64 = torch.zeros(2, 3, dtype=torch.float64)
print(tensor_float64)
print(tensor_float64.dtype)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
torch.float64


In [32]:
double_points = torch.ones(10,2,dtype=torch.double)
short_points = torch.tensor([[1,2],[3,4]],dtype=torch.short)
short_points.dtype

torch.int16

In [33]:
double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

double_points = torch.zeros(10,2).to(torch.double)
short_points = torch.ones(10,2).to(dtype=torch.short)

In [34]:
points_64 = torch.rand(5, dtype= torch.double)
points_short = points_64.to(torch.short)
points_short.dtype, points_64 * points_short

(torch.int16, tensor([0., 0., 0., 0., 0.], dtype=torch.float64))

In [35]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a.shape , a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [36]:
a_t = a.transpose(0,1)
a_t.shape

torch.Size([2, 3])

In [37]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage()

C:\Users\user\AppData\Local\Temp\ipykernel_16068\3684768117.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [38]:
points_storage = points.storage()
points_storage[0]

4.0

In [39]:
points.storage()[1]

1.0

In [40]:
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [41]:
a = torch.ones(3,2)
a.zero_
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [42]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_points = points[1]
second_points, second_points.storage_offset(), second_points.size()

(tensor([5., 3.]), 2, torch.Size([2]))

In [43]:
second_points.shape, points.stride()

(torch.Size([2]), (2, 1))

In [44]:
p = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
s_p = p[1]
s_p, s_p.storage_offset(), s_p.size(), s_p.shape, p.stride(), p.size()

(tensor([4., 5., 6.]),
 3,
 torch.Size([3]),
 torch.Size([3]),
 (3, 1),
 torch.Size([3, 3]))

In [45]:
second_points = points[1]
second_points.size(), second_points.storage_offset(),second_points.stride()

(torch.Size([2]), 2, (1,))

In [46]:
second_points[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [47]:
second_points = points[1].clone()
second_points[0] = 10.0
second_points, points

(tensor([10.,  3.]),
 tensor([[ 4.,  1.],
         [10.,  3.],
         [ 2.,  1.]]))

In [48]:
a = [1, 2, 3]
b = a
c = [1, 2, 3]

print(id(a))  # a의 id 출력
print(id(b))  # b의 id 출력 (a와 동일)
print(id(c))  # c의 id 출력 (a와 다름)


2896047952576
2896047952576
2896047948224


In [49]:
points1 = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points1_t = points1.t()
points1_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [50]:
id(points1.storage()) == id(points1_t.storage())

False

In [51]:
points1.stride(), points1_t.stride()

((2, 1), (1, 2))

In [52]:
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
print(some_t.shape, transpose_t.shape) 
print(some_t.stride(), transpose_t.stride())

torch.Size([3, 4, 5]) torch.Size([5, 4, 3])
(20, 5, 1) (1, 5, 20)


In [53]:
# import torch

# # 3x2 텐서 생성
# points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

# # 텐서를 전치하여 2x3 텐서 생성
# points_t = points.t()

# # 전치된 텐서가 연속적이지 않음을 확인
# print("Is points_t contiguous?", points_t.is_contiguous())

# # 연속적 메모리 배치를 가진 새로운 텐서 생성
# points_t_contiguous = points_t.contiguous()

# # 새로운 텐서가 연속적인지 확인
# print("Is points_t_contiguous contiguous?", points_t_contiguous.is_contiguous())


In [54]:
# points_t, points_t_contiguous

In [55]:
points1.is_contiguous(), points1_t.is_contiguous()

(True, False)

In [56]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_t = points.t()

In [57]:
points, points.storage(), points.stride()

(tensor([[4., 1.],
         [5., 3.],
         [2., 1.]]),
  4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 (2, 1))

In [58]:
points_t, points_t.storage(),points_t.stride()

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
  4.0
  1.0
  5.0
  3.0
  2.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 (1, 2))

In [59]:
points_t_cont = points_t.contiguous()
points_t_cont, points_t_cont.storage(), points_t_cont.stride()

(tensor([[4., 5., 2.],
         [1., 3., 1.]]),
  4.0
  5.0
  2.0
  1.0
  3.0
  1.0
 [torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6],
 (3, 1))

In [60]:
# points_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]],device='cuda')
points_gpu = points.to(device='cuda:0')

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points = 2 * points
points

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]])

In [ ]:
points = points + 4
points

tensor([[12.,  6.],
        [14., 10.],
        [ 8.,  6.]])

In [ ]:
import numpy as np
import torch

# 1. 넘파이 배열 생성
numpy_array = np.array([[1, 2, 3], [4, 5, 6]])

# 2. 넘파이 배열을 파이썬 리스트로 변환
python_list = numpy_array.tolist()
print("Python List:")
print(python_list)

# 3. 파이썬 리스트를 PyTorch 텐서로 변환
tensor = torch.tensor(python_list)
print("\nPyTorch Tensor:")
print(tensor)


Python List:
[[1, 2, 3], [4, 5, 6]]

PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [61]:
import torch
torch.save(points,'../data/p1ch3/ourpoints.t')

RuntimeError: Parent directory ../data/p1ch3 does not exist.

In [88]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
a, a.size(),a.storage_offset(),a.stride()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]), 0, (1,))

In [90]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [91]:
id(a.storage()) == id(b.storage())

True

In [93]:
c = b[1:,1:]
c, c.size(), c.storage_offset(), c.stride(), c.storage()

(tensor([[4, 5],
         [7, 8]]),
 torch.Size([2, 2]),
 4,
 (3, 1),
  0
  1
  2
  3
  4
  5
  6
  7
  8
 [torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9])

In [102]:
p = torch.ones(3,4)
p1 = p.tolist()
p1

[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]

In [103]:
import numpy as np

np.array(p1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [114]:
a = torch.rand(3,4).unsqueeze(-1)
a.shape

torch.Size([3, 1, 4])